AWSTemplateFormatVersion: 2010-09-09
Description: "Create EC2 instance with SSH access"
Parameters:
  KeyName:
    Type: String
    Description: "Key name to SSH to VM's. Leave blank to not associate a key."
    Default: "llavenuda"
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0f599bbc07afc299a
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref SSHSecurityGroup
      Tags:
        - Key: Name
          Value: MyEC2Instance
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join ["-", [ssh-security-group, dev]]
      GroupDescription: "Allow SSH traffic"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  myPatchBaseline:
    Type: AWS::SSM::PatchBaseline
    Properties:
      Name: SecurityUpdates
      Description: Baseline for only patching security updates
      OperatingSystem: AMAZON_LINUX_2 ##
      PatchGroups: ##
        - myPatchGroup
      ApprovalRules: # Obligatorio
        PatchRules:
          - ApproveAfterDays: "7"
            PatchFilterGroup:
              PatchFilters:
                - Key: CLASSIFICATION # Solo
                  Values:
                    - Security
                - Key: SEVERITY
                  Values:
                    - Critical
                    - Important
